services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\PurchaseCreditsBundle\Controller\:
        resource: '../../Controller/*'

    c975L\PurchaseCreditsBundle\Service\:
        resource: '../../Service/*'

    c975L\PurchaseCreditsBundle\Twig\:
        resource: '../../Twig/*'
